---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp
  name: myapp
spec:
  clusterIP: None
  ports:
    - port: 2551
      protocol: TCP
      targetPort: 2551
  selector:
    app: myapp
