- hosts: all
  vars:
    pip_install_packages:
      - name: docker
      - name: docker-compose
    docker_apt_release_channel: stable
    docker_apt_arch: amd64
    docker_apt_repository: "deb [arch={{ docker_apt_arch }}] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"
    docker_apt_ignore_key_error: True
    docker_install_compose: false
    docker_compose_path: /usr/local/bin/docker-compose
    docker_compose_version: "1.23.2"
    pip_package: python3-pip
  roles:
    - role: geerlingguy.pip
      tags: init_server
      become: yes
    - role: geerlingguy.docker
      tags: init_server
      become: yes
  tasks:
    - name: Creates directory 1
      file:
        path: /opt/upsidemind/public
        state: directory
      tags:
        - deploy
    - synchronize:
        src: ../frontend/build/
        dest: /opt/upsidemind/public/
        delete: yes
        recursive: yes
      tags:
        - deploy
    - name: Creates directory 2
      file:
        path: /opt/upsidemind/gateway
        state: directory
      tags:
        - deploy
    - synchronize:
        src: gateway/
        dest: /opt/upsidemind/gateway/
        #delete: yes
        recursive: yes
      tags:
        - deploy

    - name: Creates directory 3
      file:
        path: /opt/upsidemind/app
        state: directory
      tags:
        - deploy

    - synchronize:
        src: ../service/target/docker/stage/
        dest: /opt/upsidemind/app/
        delete: yes
        recursive: yes
      tags:
        - deploy

    - docker_service:
        project_src: /opt/upsidemind/gateway
        state: absent
      tags:
        - deploy

    - docker_service:
        project_src: /opt/upsidemind/gateway
      register: output
      tags:
        - deploy

    - debug:
        var: output
      tags:
        - deploy

    - docker_service:
        project_src: /opt/upsidemind/gateway
        build: no
      register: output
      tags:
        - deploy

    - debug:
        var: output
      tags:
        - deploy

    - assert:
        that: "not output.changed "
      tags: deploy

    - docker_service:
        project_src: /opt/upsidemind/gateway
        build: no
        stopped: true
      register: output
      tags:
        - deploy

    - debug:
        var: output
      tags:
        - deploy

    - assert:
        that:
          - "not nginx.gateway_nginx_1.state.running"
      tags:
        - deploy

    - docker_service:
        project_src: /opt/upsidemind/gateway
        build: no
        restarted: true
      register: output
      tags:
        - deploy

    - debug:
        var: output
      tags:
        - deploy

    - assert:
        that:
          - "nginx.gateway_nginx_1.state.running"
      tags:
        - deploy
