---
- name: Update apt
  apt:
    update_cache: yes
    cache_valid_time: 3600
- name: Install nginx
  apt:
    name: nginx
    state: present
- name: Replace nginx config
  template: 
    src=templates/nginx.conf
    dest=/etc/nginx/nginx.conf
  notify:
    - nginx reload
- name: Enable service nginx and ensure it is not masked
  ansible.builtin.systemd:
    name: nginx
    enabled: yes
    masked: no
