= Hello, AsciiDoc!

Rubies are red, +
Topazes are blue.

I can't believe it, we *won*!

bold *constrained* & **un**constrained

italic _constrained_ & __un__constrained

bold italic *_constrained_* & **__un__**constrained

monospace `constrained` & ``un``constrained

monospace bold `*constrained*` & ``**un**``constrained

monospace italic `_constrained_` & ``__un__``constrained

monospace bold italic `*_constrained_*` & ``**__un__**``constrained

\*Stars* will appear as *Stars*, not as bold text.

\&sect; will appear as an entity, not the &sect; symbol.

\\__func__ will appear as __func__, not as emphasized text.

\{two-semicolons} will appear {two-semicolons}, not resolved as ;;.

The text pass:[<u>underline me</u>] is underlined.

+++content passed directly to the output+++ followed by normal content.

The text +++<u>underline me</u>+++ is underlined.

This +*literal*+ will appear as *literal*.

* Edgar Allan Poe
* Sheri S. Tepper
* Bill Bryson

.Kizmet's Favorite Authors
* Edgar Allan Poe
* Sheri S. Tepper
* Bill Bryson

* Apples
* Oranges

//-

* Walnuts
* Almonds

.Possible DefOps manual locations
* West wood maze
** Maze heart
*** Reflection pool
** Secret exit
* Untracked file in git repository

* level 1
** level 2
*** level 3
**** level 4
***** level 5
* level 1

---

. Protons
. Electrons
. Neutrons

---

[start=4]
. Step four
. Step five
. Step six

---

[%reversed]
.Parts of an atom
. Protons
. Electrons
. Neutrons

---

. Step 1
. Step 2
.. Step 2a
.. Step 2b
. Step 3

---

. Linux
* Fedora
* Ubuntu
* Slackware
. BSD
* FreeBSD
* NetBSD

---

[lowerroman, start=5]
. Five
. Six
[loweralpha]
.. a
.. b
.. c
. Seven

---

CPU:: The brain of the computer.
Hard drive:: Permanent storage for operating system and/or user files.
RAM:: Temporarily stores information the CPU uses during operation.
Keyboard:: Used to enter text or control items on the screen.
Mouse:: Used to point to and select items on your computer screen.
Monitor:: Displays information in visual form using text and graphics.

---

[horizontal]
CPU:: The brain of the computer.
Hard drive:: Permanent storage for operating system and/or user files.
RAM:: Temporarily stores information the CPU uses during operation.

---

Dairy::
* Milk
* Eggs
Bakery::
* Bread
Produce::
* Bananas

---

Operating Systems::
  Linux:::
    . Fedora
      * Desktop
    . Ubuntu
      * Desktop
      * Server
  BSD:::
    . FreeBSD
    . NetBSD

Cloud Providers::
  PaaS:::
    . OpenShift
    . CloudBees
  IaaS:::
    . Amazon EC2
    . Rackspace

