addSbtPlugin("de.heikoseeberger"  % "sbt-header"          % "5.2.0")
addSbtPlugin("org.scalariform"    % "sbt-scalariform"     % "1.8.3")
addSbtPlugin("com.typesafe.sbt"   % "sbt-native-packager" % "1.4.1")
addSbtPlugin("io.spray"           % "sbt-revolver"        % "0.9.1")
addSbtPlugin("org.scoverage"      % "sbt-scoverage"       % "1.5.1")
