help:
	@echo  "PostgreSQL Demo Repo"
  
# see: https://www.postgresql.org/docs/14/tutorial-createdb.html
createdb:
	createdb mydb

# see: https://www.postgresql.org/docs/14/tutorial-createdb.html
dropdb:
	dropdb mydb
  
# see: https://www.postgresql.org/docs/14/tutorial-accessdb.html
shell:
	psql mydb

# see: https://www.postgresql.org/docs/14/tutorial-accessdb.html
version:
	psql -d mydb -c "SELECT version()"
