version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: reverse_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
      #- /etc/ssl:/etc/ssl
    ports:
      - "80:80"
      - "443:443"
    links:
      - bootzooka
  bootzooka:
    image: 'softwaremill/bootzooka:latest'
    ports: []
      #- '8080:8080'
    links:
      - bootzooka-db
    environment:
      SQL_USERNAME: 'postgres'
      SQL_PASSWORD: 'b00t200k4'
      SQL_DBNAME: 'bootzooka'
      SQL_HOST: 'bootzooka-db'
      SQL_PORT: '5432'
      API_HOST: '0.0.0.0'
      SMTP_ENABLED: 'false'
      MAILGUN_ENABLED: 'true'
      MAILGUN_URL: 'https://api.eu.mailgun.net/v3/mail.assistant.manenkov.com/messages'
      MAILGUN_API_KEY: 'SECRET'
      MAILGUN_DOMAIN: 'mail.assistant.manenkov.com'
      MAILGUN_SENDER_NAME: 'info'
      MAILGUN_SENDER_DISPLAY_NAME: 'Ассистент'
      PASSWORD_RESET_LINK_PATTERN: 'https://assistant.manenkov.com/password-reset?code=%s'
  bootzooka-db:
    image: 'postgres'
    volumes:
      - /root/assistant-private/var/lib/postgresql:/var/lib/postgresql
    ports: []
      #- '25432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'b00t200k4'
      POSTGRES_DB: 'bootzooka'
